apiVersion: batch/v1
kind: Job
metadata:
  name: kubespray
spec:
  template:
    spec:
      containers:
      - name: kubespray
        image: lailemon/demo:demo
        command: ["ansible-inventory","--version"]
      restartPolicy: Never
  backoffLimit: 4
